# request succeeds if status 200
# resource created: 201
#GET http://localhost:5500/

#request
#POST http://localhost:5500/api/v1/auth/sign-up  
#header
#Content-Type: application/json
#space to separate header and body is necessary

#body
# #{
#     "name": "Emily",
#     "email": "ej@gmail.com",
#     "password": "1234"
# }

# POST http://localhost:5500/api/v1/auth/sign-in
# #header
# Content-Type: application/json
# #space to separate header and body is necessary

# #body
# {
#     "email": "ej@gmail.com",
#     "password": "1234"
# }

# GET http://localhost:5500/api/v1/users/68c6378705fa0a40ce8ed37c
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGM2Mzc4NzA1ZmEwYTQwY2U4ZWQzN2MiLCJpYXQiOjE3NTc4MjQ3MjAsImV4cCI6MTc1NzkxMTEyMH0.efnP-UO5_HSVmZV2bKjRRhXJMReD70KHJeWv0BFmMq4
# Content-Type: application/json


# GET http://localhost:5500/api/v1/subscriptions/user/68c6378705fa0a40ce8ed37c
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGM2Mzc4NzA1ZmEwYTQwY2U4ZWQzN2MiLCJpYXQiOjE3NTc4MjQ3MjAsImV4cCI6MTc1NzkxMTEyMH0.efnP-UO5_HSVmZV2bKjRRhXJMReD70KHJeWv0BFmMq4
# Content-Type: application/json

# {
#     "name": "Netflix Premium",
#     "price": 15.99,
#     "currency": "USD",
#     "frequency": "monthly",
#     "category": "entertainment",
#     "startDate": "2024-02-01T00:00:00.000Z",
#     "paymentMethod": "Credit Card"
# }

POST http://localhost:5500/api/v1/subscriptions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGM2Mzc4NzA1ZmEwYTQwY2U4ZWQzN2MiLCJpYXQiOjE3NTc4MjQ3MjAsImV4cCI6MTc1NzkxMTEyMH0.efnP-UO5_HSVmZV2bKjRRhXJMReD70KHJeWv0BFmMq4
Content-Type: application/json

# {
#     "name": "JS Membership",
#     "price": 135.99,
#     "currency": "USD",
#     "frequency": "monthly",
#     "category": "entertainment",
#     "startDate": "2025-09-14T00:00:00.000Z",
#     "paymentMethod": "Credit Card"
# }

{
    "name": "Amazon Prime",
    "price": 130.99,
    "currency": "USD",
    "frequency": "monthly",
    "category": "entertainment",
    "startDate": "2025-09-14T17:50:00.000Z",
    "paymentMethod": "Credit Card"
}